AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
LineLength:
  Max: 100

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
    - "require"
    - "source"
    - "task"
    - "add_dependency"
    - "add_development_dependency"
    - "yield"
    - "raise"
    - "to"
    - "not_to"
    - "include"
    - "is_a?"
    - "eq"
    - "eql"
    - "be"
  AllowParenthesesInMultilineCall: false
  AllowParenthesesInChaining: false
  AllowParenthesesInCamelCaseMethod: false
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - omit_parentheses
